jobs:
  include:
  - install:
    - pip install poetry
    - poetry install
    script: yeyo dev test
    language: python
    dist: xenial
    sudo: required
    python:
    - '3.7'
  - install:
    - pip install poetry
    - poetry install
    script: yeyo dev test
    language: python
    dist: xenial
    sudo: required
    python:
    - '3.6'
